#include "VuforiaController.h"
#include <format>

extern void garnishLog(const std::string &logstr);

ErrorCode VuforiaController::initAR(const std::string &licensekey) {
    garnishLog(std::format("VuforiaController::initAR() start{}", "."));

    return ErrorCode::None;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_DRIVER_CONFIG_LOAD_ERROR;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_DRIVER_CONFIG_FEATURE_NOT_SUPPORTED;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_LICENSE_CONFIG_MISSING_KEY;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_LICENSE_CONFIG_INVALID_KEY;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_LICENSE_CONFIG_NO_NETWORK_PERMANENT;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_LICENSE_CONFIG_NO_NETWORK_TRANSIENT;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_LICENSE_CONFIG_BAD_REQUEST;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_LICENSE_CONFIG_KEY_CANCELED;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_LICENSE_CONFIG_PRODUCT_TYPE_MISMATCH;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_LICENSE_CONFIG_UNKNOWN;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_RENDER_CONFIG_UNSUPPORTED_BACKEND;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_RENDER_CONFIG_FAILED_TO_SET_VIDEO_BG_VIEWPORT;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_PLATFORM_ANDROID_CONFIG_INITIALIZATION_ERROR;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_PLATFORM_ANDROID_CONFIG_INVALID_ACTIVITY;
//    return ErrorCode::VU_ENGINE_CREATION_ERROR_PLATFORM_ANDROID_CONFIG_INVALID_JAVA_VM;
//    return ErrorCode::VU_ENGINE_ERROR_INVALID_LICENSE;
//    return ErrorCode::VU_ENGINE_ERROR_CAMERA_DEVICE_LOST;
//    return ErrorCode::VU_ENGINE_ERROR_PLATFORM_FUSION_PROVIDER_INFO_INVALIDATED;
}
